### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#11]
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't been published yet, this should be done before RC testing and publishing.

**Comment by veillette** [comment]
I forgot to tag the commit b4a860366c71851b2137f1648ed4d57e4cf6fd3a which resets the temperature property. 

PropertySet was converted to Property. The reset button does not fully work because of the flawed approach used to Zoom in and out. Since this is tracked in an other issue (see #13) I'll close this one.
