### ISSUE TITLE
User question: slope, Wien's displacement

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/blackbody-spectrum#12]
> Hi, I use the blackbody radiation simulation and photoelectric effect simulation to introduce my students in to the particle model of light and quantum mechanics.  For the blackbody radiation lab, I have my students graph peak frequency vs. temperature to see that it is a direct relationship.  The shape of the graph looks great, but my students and I all get a slope of about 1 x 1011 s-1K-1.  According to Wiem’s displacement law it should be 5.88 x 1010 s-1K-1.  Are we doing something wrong?

**Comment by veillette** [comment]
The simulation is correct (both flash and the Html5 prototype). The issue that the user encountered is due to some well documented misunderstanding. It is a rather subtle issue that has to do with the measure. of the distribution function. It is elaborated in more details in the following links 

-http://physics.stackexchange.com/questions/211049/frequency-and-wavelength-peak-for-wiens-displaement-law-of-a-blackbody
-http://physics.stackexchange.com/questions/13611/plancks-law-in-terms-of-wavelength
-http://physics.stackexchange.com/questions/91192/the-strange-thing-about-the-maximum-in-plancks-law

It would be preferable to plot lambda peak versus the inverse temperature.  Lambda peak is easily measurable in our simulation. 

@oliver-phet : You may want to relay this information to the user.

**Comment by oliver-phet** [comment]
@veillette Thanks! Response to user sent. I'll reopen if they have questions.
