### ISSUE TITLE
BlackbodySpectrumThermometer uses private knowledge about ThermometerNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#18]
Related to #15 (code review)...  

In `BlackbodySpectrumThermometer`:

```js
/**
   * map function that relates a temperature to a height
   * this function was reverse engineered from ThermometerNode in Scenery-Phet
   * @param {Object} options - options that were provided to BlackbodySpectrumThermometer constructor
   * @returns {LinearFunction}
   */
  var temperatureToHeightLinearFunction = function( options ) {
```

The comment "this function was reverse engineered from ThermometerNode in Scenery-Phet" is a red flag.  If it was reverse engineered, then changes to `ThermometerNode` may break this.   If would be better to add needed functionality to `ThermometerNode`.

**Comment by arnabp** [comment]
The function didn't seem like it was dependent on knowledge of ThermometerNode. Looks like the function used thermometer node methods as an outline, removed comment to avoid confusion. @pixelzoom Does this look okay to you or did you see something specific here?

**Comment by veillette** [comment]
@arnabp: I think that @pixelzoom  meant that this construction is inherently fragile since changes to private variables (that would affect say the layout of a thermometer) of ThermometerNode would break BlackbodySpectrumThermometer. 

The temperatureToHeightLinearFunction could live within Thermometer node, such that a client could decorate a thermometer with tick marks without having to understand  all the geometry of the ThermometerNode in order to determine the location of a tick mark.
Alternatively, one can envision a getter that would return the position tickMark given a temperature.

**Comment by pixelzoom** [comment]
Yes @veillette, exactly.  The purpose of this function is to determine where the tick marks are located, and that's a (currently internal) implementation detail of ThermometerNode.  If we need to determine where ticks are (or better yet, label ticks) that functionality should be provided by ThermometerNode.

**Comment by arnabp** [comment]
Assigning to @jbphet for code review

**Comment by jbphet** [comment]
Reviewed and discussed with @arnabp, looks good, closing.
