### ISSUE TITLE
Where to put intensity label when curve moves off screen

### ISSUE THREAD

**Issue by arnabp** [phetsims/blackbody-spectrum#25]
In the [latest dev build](https://bayes.colorado.edu/dev/html/blackbody-spectrum/1.0.0-dev.4/phet/blackbody-spectrum_en_phet.html) I've run into some trouble with where to put the text label when the curve becomes too large or too small.

The current implementation has the text stop when it hits the right border of the graph (when temperature becomes too small, or graph is zoomed in to the left of the peak). It also stops just above the tick marks while moving down (when temperature becomes too small). Some other options might be to allow the text to move past the bounds of the graph, or have it continue to move but allow the text to disappear as it moves past the border of the graph. 

For higher temperatures, when the text gets too high it will continue to rise past the border of the graph, then the border of the sim. Options here include having it stop at the upper border of the sim, or the upper border of the graph (or leaving it as is).

**Comment by DianaTavares** [comment]
In my opinion:

 I like the actual behavior that you create: when the curve get smaller, the user can still read the text and it move to the peak position to the corner of the graph, but I think that may be good idea to add a little arrow close to the number when the peak is out of the graph values, because I think that give an idea to the user of use the zooms elements to see the peak position. 
![screen shot 2018-04-13 at 3 19 05 pm](https://user-images.githubusercontent.com/26031501/38758422-22a12b14-3f2e-11e8-9667-c75b8aa4fa8e.png)

I suggest the same action when the curve get bigger, the number move with the curve up, but when the curve is much bigger, the number still in the graph, in that way the user can read the vale and a little arrow too, that indicate that the peak is taller. 

![screen shot 2018-04-13 at 3 29 31 pm](https://user-images.githubusercontent.com/26031501/38758732-a176216e-3f2f-11e8-844e-708aaaf5cfc8.png)

 

I don't  think is good to get the numbers over the vertical axe. It's better to stop the label just before  the numbers touch the axe. 

![screen shot 2018-04-13 at 3 23 48 pm](https://user-images.githubusercontent.com/26031501/38758546-b3ac49a4-3f2e-11e8-8fdd-144e88d8a80e.png)

What do you think  @ariel-phet ?

**Comment by ariel-phet** [comment]
Seems like this would be good to discuss at design meeting. I will talk with @DianaTavares for some various ideas

**Comment by DianaTavares** [comment]
Already implemented and looks amazing! closing
