### ISSUE TITLE
UI adjustments (aka "pixel polishing), round 1

### ISSUE THREAD

**Issue by jbphet** [phetsims/blackbody-spectrum#34]
In the 9/20/2018 sim design meeting we reviewed the [1.0.0-dev.10 dev version](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.10/phet/blackbody-spectrum_en_phet.html) for UI adjustments.  Here is the TODO list that resulted:

- [x] make the temperature adjustment triangle significantly larger and closer
- [x] make the arrow cues significantly larger
- [x] get rid of big vertical white line that is just to the right of the thermometer
- [x] add a thin dotted line from the adjustment triangle to the thermometer
- [x] use the camera and eraser icons, side by side, instead of the current save and erase button
- [x] reduce size of check boxes a bit (use a relatively recently published Masses & Springs sim as a guide)
- [x] make graph axes label white
- [x] make the zoom buttons a bit smaller, usage M&S again as a guide

I think there may have been a couple of things that were discussed early in the meeting that I didn't get in here - @arnabp feel free to add anything that you recall.

**Comment by arnabp** [comment]
Made the adjustments listed, you can view them in [1.0.0-dev.11 dev version](https://phet-dev.colorado.edu/html/blackbody-spectrum/1.0.0-dev.11/phet/blackbody-spectrum_en_phet.html). Let me know how this looks!

**Comment by DianaTavares** [comment]
I like the new changes, good job @arnabp! I have some observations: 

- I think that the cues arrows for the Graph Values should be the same side that the ones in the thermometer. 
- Now that all the text is white, should the BGR letters be white as well?
- The default y-axes when the sim start or refresh it's 300, I think that can be 100, because the curve looks very small. 
- I feel the camera and eraser icons big, but probably it's because the checkboxes are small compared with the buttons. should be blue like the zoom buttons? 
- I think that the "Blackbody Temperature" text above the thermometer should be the same side that the labels of the axes in the graph.
- In the design document I wrote time ago that when the dot of Graph Values was in the peak of the graph,  It has other color different to green (It is pink in the design document), in that case, student can identify when it's looking the values of the peak when it's moving the dot. Is it necessary to include this behavior?
- When the graph is bigger the the axes values and the Graph values is active, I think that it's strange to see the value of the y-coordinate green below the levels of the graph. I suggest to disappears this number when the value it's bigger that the labels of the graph, like the yellow dash line disappears. 
![screen shot 2018-10-10 at 5 56 28 pm](https://user-images.githubusercontent.com/26031501/46772807-1f3d6980-ccb7-11e8-9a41-b88598560f29.png)

These are some comments, let's see what @ariel-phet think.

**Comment by DianaTavares** [comment]
Today we have the pixel polishing round 2! We review the information in my last comment and other things. I am going to close this issue and open a new one with the list of the agreements in today meeting.
