### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/blackbody-spectrum#4]
Looks like this sim has some red-on-black issues, caused by using 'red' color. Evaluate whether to use PhetColorScheme.RED_COLORBLIND.

**Comment by jbphet** [comment]
I think it would be inappropriate to use RED_COLORBLIND for the spectrum or the B-G-R displays, since the actual color value is meaningful in this context.  That leaves the line on the graph and the contents of the thermometer.  I tried changing both to RED_COLORBLIND, and in my opinion it looked pretty good for the line on the graph, but it didn't look good for the thermometer and it didn't look any better to my eye when testing with the Chrome "Colorblinding" plugin.  My recommendation would be to change only the value for the graph curve stroke.  This may cause us to want a different color from what is currently used for saved curves, since they seem a bit less distinct to me.  Assigning to @DianaTavares to finalize the decision.  Once we know what needs to be done, please assign it to @SaurabhTotey for implementation.

Here is the current master version:

![image](https://user-images.githubusercontent.com/3082831/42065354-ba69c604-7af7-11e8-9227-da22b331a761.png)

Here is the master version with RED_COLORBLIND for the curve and the thermometer color:

![image](https://user-images.githubusercontent.com/3082831/42065459-43dbfbbe-7af8-11e8-8399-706e81f50854.png)

Here is the same change with a saved curve:

![image](https://user-images.githubusercontent.com/3082831/42065627-4518be44-7af9-11e8-91f0-b4446f02c9a7.png)

**Comment by DianaTavares** [comment]
@jbphet its right, the thermometer don't looks good in the RED_COLORBLIND, but the graphs looks very well, an it's better because the visible spectrum doesn't have that color and the curve it's visible all the time. 

Now, about the saved curve, I choose brown because it's a color that isn't in the visible spectrum. But we can use the gray color that is used in other sims (like graphing lines) for saved graphs. I think that it looks good in the mockup
![screen shot 2018-07-18 at 9 59 40 am](https://user-images.githubusercontent.com/26031501/42893342-52a915fe-8a71-11e8-9c10-b4f95d82cffe.png)

**Comment by ariel-phet** [comment]
I believe this can be closed.
