### ISSUE TITLE
RTL Labels do not break up spectrum

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/blackbody-spectrum#94]
**Device**
Chadwick
**OS**
ChromeOS
**Browser**
74.0.3729.159
**Problem Description**
For https://github.com/phetsims/QA/issues/320
When stringTest=rtl, the labels of various parts of the spectrum do not show up.  No tick marks appear when they should.  Only one string shows up centered on the graph, no matter where the various spectrum bars are
**Steps to Reproduce**
1. stringTest=rtl
2. Turn on labels
3. Zoom x-axis in and out.  Observe

**Screenshots**
![nolabels](https://user-images.githubusercontent.com/41024075/58207926-eb8cde00-7ca0-11e9-8fd0-238f2bdbbd00.gif)

**Comment by DianaTavares** [comment]
definitely a bug that have to be fix

**Comment by arnabp** [comment]
This is something that comes up if you do any stringtest that's not double, because the implementation for the labels depends on the names for the different wavelengths being different. Because most stringtests replace every string with the same word, the spectrum label combines all of them. 

I don't, however, see this being a problem outside of testing purposes I believe? Translations should have different words for each type of light and if a language does happen to use the same name for, say, xray and ultraviolet, having the two sections combine would make sense.

**Comment by arnabp** [comment]
Discussed this with @jbphet and decided it was risky to use strings as keys in an Object. Moved away from that, which allows the label text to behave as expected. RTL, x, and any other stringtests will now break up the spectrum properly, closing.
